### ISSUE TITLE
I ALSO WANT TO CONTRIBUTE ON THIS PROJECT

### ISSUE THREAD

**Issue by xshshahab** [AhmadAltamash/Auto-Mobile-Servicing#1]
# Hii, AhmadAltamash

**I came across your project on GitHub related to automobile servicing, and I’m really interested in contributing. However, I noticed that there isn’t much information available about the project’s purpose or the technologies it uses.**

**Could you please provide a brief overview of what this project is about and which technology stack it is based on? Additionally, I’d love to understand how I can contribute effectively.**

Document the project: I can help create or improve the README file with setup instructions, usage guidelines, and other relevant details.
Enhance the codebase: I can contribute by fixing bugs, adding new features, or improving existing functionalities.
Organize issues: I can help by identifying and documenting issues or feature requests, and working on them.
Thank you for your time and looking forward to your response!

Best regards,
[ Md. Shahabuddin ]

**Comment by AhmadAltamash** [comment]
This Project is about an Automobile Servicing web based application for Servicing company which enable the customers to book there monthly services online or any other services regarding there vehicle either it's two or four wheeler., It's a full stack web application where I chose CSS for styling, JS for authentication and JSP for Backend Writing that enables to fetch data from SQL(postgreSQL) and other activities like adding services, plans or enquiring about customers and there details ; this will be done by the admin, where he can check whether the service is done or not. After servicing he'll send the vehicle for check out where customer will get the information for there vehicle so that he will easily get his vehicle without waiting in queue.
The project is still under process, only it's billing and payment gateway method is left. Nonetheless, I couldn't find any free payment gateway method, if you know something about it please help.., May Allah Reward you for this.
Jazakallah

**Comment by xshshahab** [comment]
As far as I know there is no free service for payment, Razorpay, Stripe, all are paid.

- **PayPal** offers a free payment gateway with transaction fees. You can start with their Standard service, which doesn't charge a setup fee, but there are fees for each transaction. You can integrate PayPal using their REST API or PayPal buttons.

- **Instamojo** provides a free payment gateway for small businesses and startups. They charge per transaction, but there's no monthly fee. They support UPI, net banking, wallets, and more, making it ideal for Indian users.


- **Cashfree** is free to set up and has transaction-based fees like most payment gateways. It supports UPI, wallets, credit cards, and debit cards.
You can easily integrate Cashfree into your web app with their APIs.

But I have not used any free service. I have used Stripe. If you want to integrate it, I can help you with that.

**Comment by AhmadAltamash** [comment]
Thanks Brother!
